/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#001b3c",
        "outline": "#8A949E",
        "surface-container-low": "#FAFBFC",
        "surface-container-high": "#F4F6F8",
        "error-container": "#FEF2F2",
        "tertiary-fixed": "#dbeafe",
        "tertiary-container": "#eff6ff",
        "on-secondary-fixed": "#0f172a",
        "on-secondary-container": "#334155",
        "on-surface-variant": "#5F6B76",
        "surface-variant": "#EEF1F4",
        "on-tertiary-fixed-variant": "#1e3a8a",
        "primary-fixed-dim": "#3b82f6",
        "on-surface": "#17212B",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#475569",
        "inverse-surface": "#17212B",
        "on-primary": "#ffffff",
        "background": "#F4F6F8",
        "surface-dim": "#EEF1F4",
        "outline-variant": "#D9DEE5",
        "inverse-on-surface": "#FAFBFC",
        "surface-container-highest": "#E5E9EE",
        "on-error-container": "#991b1b",
        "secondary-fixed": "#f1f5f9",
        "surface": "#FFFFFF",
        "surface-container": "#FFFFFF",
        "surface-bright": "#FFFFFF",
        "primary-fixed": "#eff6ff",
        "on-background": "#17212B",
        "tertiary": "#0284c7",
        "on-primary-fixed": "#1e3a8a",
        "primary-container": "#eff6ff",
        "surface-container-lowest": "#FFFFFF",
        "inverse-primary": "#2563eb",
        "on-primary-fixed-variant": "#1d4ed8",
        "on-tertiary-container": "#0369a1",
        "on-secondary": "#1e293b",
        "surface-tint": "#2563eb",
        "error": "#ef4444",
        "secondary-container": "#f1f5f9",
        "secondary": "#64748b",
        "on-primary-container": "#1e40af",
        "primary": "#2563eb",
        "secondary-fixed-dim": "#94a3b8",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#bae6fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.625rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "container-max": "1440px",
        "lg": "24px",
        "unit": "4px",
        "xl": "48px",
        "gutter": "24px",
        "sm": "8px",
        "xs": "4px",
        "md": "16px"
      },
      fontFamily: {
        "display": ["'Sora'", "'Space Grotesk'", "sans-serif"],
        "display-lg": ["'Sora'", "sans-serif"],
        "display-lg-mobile": ["'Sora'", "sans-serif"],
        "headline-md": ["'Sora'", "sans-serif"],
        "label-caps": ["'Inter'", "'Space Grotesk'", "sans-serif"],
        "body-lg": ["'Inter'", "'Space Grotesk'", "sans-serif"],
        "body-md": ["'Inter'", "'Space Grotesk'", "sans-serif"],
        "body-sm": ["'Inter'", "'Space Grotesk'", "sans-serif"],
        "technical-md": ["'JetBrains Mono'", "monospace"],
        "technical-sm": ["'JetBrains Mono'", "monospace"],
        "data-mono": ["'JetBrains Mono'", "monospace"],
        sans: ["'Inter'", "'Space Grotesk'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "700" }],
        "technical-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "display-lg-mobile": ["32px", { "lineHeight": "38px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "technical-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
      }
    }
  },
  plugins: [],
}
