# -*- coding: utf-8 -*-
"""VPNVision_Flow_Engine_Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AEW90puT4U2nsMTpUjYqLe-OQuf5FXBy
"""

# from google.colab import drive

from pathlib import Path

PROJECT_PATH = Path(__file__).resolve().parent

RAW_PATH = PROJECT_PATH / "raw"
PROCESSED_PATH = PROJECT_PATH / "processed"
PREPROCESSING_PATH = PROJECT_PATH / "preprocessing"
MODELS_PATH = PROJECT_PATH / "models"
REPORTS_PATH = PROJECT_PATH / "reports"

print(PROJECT_PATH)

import os

csv_path = RAW_PATH / "consolidated_traffic_data.csv"

print("CSV exists:", os.path.exists(csv_path))
print("CSV path:", csv_path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries imported successfully")

df = pd.read_csv(csv_path)

print("Dataset loaded successfully")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

df.tail()

print(df.columns.tolist())

df.describe().T

missing = df.isnull().sum()

print(missing)
missing[missing > 0]

numeric_df = df.select_dtypes(include=np.number)

infinite_counts = np.isinf(numeric_df).sum()

print(infinite_counts[infinite_counts > 0])

duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

constant_columns = [
    col for col in df.columns
    if df[col].nunique(dropna=False) <= 1
]

print("Constant columns:")
print(constant_columns)

print(df['traffic_type'].value_counts())

print("Number of traffic classes:",
      df['traffic_type'].nunique())

print("Traffic classes:")
print(df['traffic_type'].unique())

class_counts = df['traffic_type'].value_counts()

print(class_counts)

class_percentages = df['traffic_type'].value_counts(normalize=True) * 100

print(class_percentages)

plt.figure(figsize=(10, 5))

class_counts.plot(kind='bar')

plt.title("Traffic Class Distribution")
plt.xlabel("Traffic Type")
plt.ylabel("Number of Flows")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

unique_counts = df.nunique().sort_values()

print(unique_counts)

numeric_columns = df.select_dtypes(include=np.number).columns.tolist()
categorical_columns = df.select_dtypes(exclude=np.number).columns.tolist()

print("Numerical columns:")
print(numeric_columns)

print("\nCategorical columns:")
print(categorical_columns)

negative_counts = (df[numeric_columns] < 0).sum()

print(negative_counts[negative_counts > 0])

df[numeric_columns].hist(
    figsize=(16, 16),
    bins=50
)

plt.tight_layout()
plt.show()

correlation_matrix = df[numeric_columns].corr()
plt.figure(figsize=(14, 10))

plt.imshow(correlation_matrix, aspect='auto')

plt.colorbar()

plt.xticks(
    range(len(numeric_columns)),
    numeric_columns,
    rotation=90
)

plt.yticks(
    range(len(numeric_columns)),
    numeric_columns
)

plt.title("Feature Correlation Matrix")

plt.tight_layout()
plt.show()

print("Target column:", "traffic_type")

feature_columns = [
    col for col in df.columns
    if col != "traffic_type"
]

print("Number of input features:", len(feature_columns))
print(feature_columns)

"""Phase - 2"""

duplicate_mask = df.duplicated(keep=False)

print("Total duplicate rows:", duplicate_mask.sum())
print("Rows involved in duplicates:", duplicate_mask.sum())

duplicate_df = df[duplicate_mask]

print("\nDuplicate class distribution:")
print(duplicate_df["traffic_type"].value_counts())

print("\nNumber of unique duplicated records:")
print(df[duplicate_mask].drop_duplicates().shape[0])

feature_columns = [
    col for col in df.columns
    if col != "traffic_type"
]

duplicate_groups = (
    df.groupby(feature_columns)["traffic_type"]
      .nunique()
)

conflicting_duplicates = duplicate_groups[
    duplicate_groups > 1
]

print("Duplicate feature groups with conflicting labels:",
      len(conflicting_duplicates))

conflicting_index = (
    df.groupby(feature_columns)["traffic_type"]
      .transform("nunique") > 1
)

conflicting_rows = df[conflicting_index]

print("Rows involved in conflicting groups:",
      len(conflicting_rows))

print("\nTraffic class distribution:")
print(conflicting_rows["traffic_type"].value_counts())

conflicting_rows.sort_values(
    feature_columns
).head(20)

# Keep only rows that do NOT belong to conflicting feature groups
df_clean = df[~conflicting_index].copy()

print("Original rows:", len(df))
print("Rows after removing conflicting groups:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

before_dedup = len(df_clean)

df_clean = df_clean.drop_duplicates(
    subset=feature_columns + ["traffic_type"]
).copy()

after_dedup = len(df_clean)

print("Rows before deduplication:", before_dedup)
print("Rows after deduplication:", after_dedup)
print("Duplicate rows removed:", before_dedup - after_dedup)

print(
    "Remaining exact duplicate rows:",
    df_clean.duplicated().sum()
)

"""There are no conflicting groups

"""

for col in numeric_columns:

    negative = df.loc[df[col] < 0, col]

    if len(negative) > 0:

        print("\n" + "=" * 60)
        print("Feature:", col)
        print("Negative count:", len(negative))
        print("Minimum:", negative.min())
        print("Maximum:", negative.max())
        print("Unique negative values:", negative.nunique())

        print("\nMost common negative values:")
        print(negative.value_counts().head(10))

negative_features = [
    'min_fiat',
    'min_biat',
    'max_fiat',
    'max_biat',
    'min_flowiat',
    'max_flowiat',
    'min_active',
    'max_active',
    'min_idle',
    'max_idle'
]

# CHANGED: apply invalid-value cleaning to the authoritative cleaned dataset.
for col in negative_features:
    df_clean.loc[df_clean[col] < 0, col] = np.nan

missing_counts = df_clean.isnull().sum()

print(missing_counts[missing_counts > 0])

print("Negative min_flowiat values:")
print(
    df.loc[df["min_flowiat"] < 0, "min_flowiat"]
      .value_counts()
      .sort_index()
)

print("\nRows with negative min_flowiat:")
display(
    df.loc[df["min_flowiat"] < 0,
           ["min_flowiat", "traffic_type"]]
    .head(30)
)

zero_counts = (df[numeric_columns] == 0).sum()

print("Zero values per feature:")
print(zero_counts[zero_counts > 0].sort_values(ascending=False))

import os

os.makedirs(PROCESSED_PATH, exist_ok=True)
os.makedirs(PREPROCESSING_PATH, exist_ok=True)
os.makedirs(MODELS_PATH, exist_ok=True)
os.makedirs(REPORTS_PATH, exist_ok=True)

cleaned_path = PROCESSED_PATH / "cleaned_traffic_data.csv"

# CHANGED: save the cleaned dataframe, not the original raw dataframe.
df_clean.to_csv(cleaned_path, index=False)

print("Cleaned dataset saved to:")
print(cleaned_path)

# ============================================
# FINAL MODEL DATA CLEANING
# ============================================

import numpy as np

# CHANGED: train from the same cleaned dataset that is saved above.
df_model = df_clean.copy()

print("Dataset shape:", df_model.shape)

print("\nNegative values remaining:")
numeric_model_columns = df_model.select_dtypes(include="number").columns
remaining_negative = (df_model[numeric_model_columns] < 0).sum()
print(remaining_negative[remaining_negative > 0])

print("\nMissing values created:")
missing = df_model.isnull().sum()
print(missing[missing > 0])

from sklearn.model_selection import train_test_split

# Separate features and target
X = df_model.drop(columns=["traffic_type"])
y = df_model["traffic_type"]

# 70% train, 15% validation, 15% test
X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    stratify=y,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    stratify=y_temp,
    random_state=42
)

print("TRAIN:", X_train.shape)
print("VALIDATION:", X_val.shape)
print("TEST:", X_test.shape)

train_df = X_train.copy()
train_df["traffic_type"] = y_train

val_df = X_val.copy()
val_df["traffic_type"] = y_val

test_df = X_test.copy()
test_df["traffic_type"] = y_test

print("TRAIN missing:")
print(train_df.isnull().sum()[train_df.isnull().sum() > 0])

print("\nVALIDATION missing:")
print(val_df.isnull().sum()[val_df.isnull().sum() > 0])

print("\nTEST missing:")
print(test_df.isnull().sum()[test_df.isnull().sum() > 0])

# ============================================
# HANDLE MISSING VALUES
# ============================================
impute_features = [
    'min_fiat', 'min_biat', 'max_fiat', 'max_biat',
    'min_flowiat', 'max_flowiat', 'min_active',
    'max_active', 'min_idle', 'max_idle'
]

print("Missing values before imputation:")

print("TRAIN:")
print(train_df[impute_features].isna().sum())

print("\nVALIDATION:")
print(val_df[impute_features].isna().sum())

print("\nTEST:")
print(test_df[impute_features].isna().sum())

train_medians = train_df[impute_features].median()

print("Training-set imputation values:")
print(train_medians)

train_df[impute_features] = train_df[impute_features].fillna(train_medians)
val_df[impute_features] = val_df[impute_features].fillna(train_medians)
test_df[impute_features] = test_df[impute_features].fillna(train_medians)

import joblib
joblib.dump(train_medians, MODELS_PATH / "imputation_medians.pkl")
print("Saved imputation medians to:", MODELS_PATH / "imputation_medians.pkl")

print("TRAIN missing:")
print(train_df.isnull().sum()[train_df.isnull().sum() > 0])

print("\nVALIDATION missing:")
print(val_df.isnull().sum()[val_df.isnull().sum() > 0])

print("\nTEST missing:")
print(test_df.isnull().sum()[test_df.isnull().sum() > 0])

numeric_features = train_df.select_dtypes(include=["number"]).columns

print("TRAIN negative values:")
print((train_df[numeric_features] < 0).sum()[
    (train_df[numeric_features] < 0).sum() > 0
])

print("\nVALIDATION negative values:")
print((val_df[numeric_features] < 0).sum()[
    (val_df[numeric_features] < 0).sum() > 0
])

print("\nTEST negative values:")
print((test_df[numeric_features] < 0).sum()[
    (test_df[numeric_features] < 0).sum() > 0
])

print("Train duplicates:", train_df.duplicated().sum())
print("Validation duplicates:", val_df.duplicated().sum())
print("Test duplicates:", test_df.duplicated().sum())

# ============================================
# ORIGINAL 23 FLOW FEATURES
# ============================================

feature_columns = [
    col for col in df.columns
    if col != "traffic_type"
]

print("Number of traffic classification features:",
      len(feature_columns))

assert len(feature_columns) == 23, f"Expected 23 features, got {len(feature_columns)}"
print(feature_columns)

print("========== FINAL CLEANING CHECK ==========")

print("\nShapes:")
print("TRAIN:", train_df.shape)
print("VALIDATION:", val_df.shape)
print("TEST:", test_df.shape)

print("\nMissing values:")
print("TRAIN:", train_df.isnull().sum().sum())
print("VALIDATION:", val_df.isnull().sum().sum())
print("TEST:", test_df.isnull().sum().sum())

numeric_cols = train_df.select_dtypes(include="number").columns

print("\nNegative values:")
print("TRAIN:", (train_df[numeric_cols] < 0).sum().sum())
print("VALIDATION:", (val_df[numeric_cols] < 0).sum().sum())
print("TEST:", (test_df[numeric_cols] < 0).sum().sum())

print("\nExact duplicates:")
print("TRAIN:", train_df.duplicated().sum())
print("VALIDATION:", val_df.duplicated().sum())
print("TEST:", test_df.duplicated().sum())

print("\nTraffic classes:")
print(train_df["traffic_type"].value_counts())

# ============================================
# SEPARATE 23 FEATURES AND TARGET
# ============================================

X_train = train_df[feature_columns].copy()
y_train = train_df["traffic_type"].copy()

X_val = val_df[feature_columns].copy()
y_val = val_df["traffic_type"].copy()

X_test = test_df[feature_columns].copy()
y_test = test_df["traffic_type"].copy()

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_val:", X_val.shape)
print("y_val:", y_val.shape)

print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("\nNumber of features:", len(feature_columns))
print("\nFeature columns:")
print(feature_columns)

print("Non-numeric columns:")
print(X_train.select_dtypes(exclude="number").columns.tolist())

print("\nData types:")
print(X_train.dtypes)

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)

y_val_encoded = label_encoder.transform(y_val)
y_test_encoded = label_encoder.transform(y_test)

print("Traffic class mapping:")
for i, class_name in enumerate(label_encoder.classes_):
    print(i, "=", class_name)

print("\nTRAIN:")
print(pd.Series(y_train_encoded).value_counts().sort_index())

print("\nVALIDATION:")
print(pd.Series(y_val_encoded).value_counts().sort_index())

print("\nTEST:")
print(pd.Series(y_test_encoded).value_counts().sort_index())

print("Train columns == Validation columns:",
      list(X_train.columns) == list(X_val.columns))

print("Train columns == Test columns:",
      list(X_train.columns) == list(X_test.columns))

print("Target present in X_train:", "traffic_type" in X_train.columns)

"""Model training - Traffic Classifier"""

from xgboost import XGBClassifier

# Create XGBoost traffic classifier
xgb_model = XGBClassifier(
    objective="multi:softprob",
    num_class=len(label_encoder.classes_),
    n_estimators=300,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="mlogloss",
    random_state=42,
    n_jobs=-1
)

print("XGBoost model created successfully.")

xgb_model.fit(
    X_train,
    y_train_encoded,
    eval_set=[
        (X_train, y_train_encoded),
        (X_val, y_val_encoded)
    ],
    verbose=True
)

print("Training completed.")

import numpy as np

# Get probabilities for all 14 classes
test_proba = xgb_model.predict_proba(X_test)

# Get Top-3 class indices for every test sample
top3_indices = np.argsort(test_proba, axis=1)[:, -3:][:, ::-1]

print("========== TOP-3 XGBOOST PREDICTIONS ==========\n")

for i in range(min(20, len(X_test))):

    print(f"Flow {i + 1}")
    print("-" * 40)

    for rank, class_index in enumerate(top3_indices[i], start=1):

        class_name = label_encoder.inverse_transform(
            [class_index]
        )[0]

        confidence = test_proba[i, class_index] * 100

        print(
            f"{rank}. {class_name:<15} "
            f"{confidence:.2f}%"
        )

    print()

results = []

for i in range(len(X_test)):

    # Top-3 class indices
    indices = top3_indices[i]

    # Top-1
    class1 = label_encoder.inverse_transform([indices[0]])[0]
    conf1 = test_proba[i, indices[0]] * 100

    # Top-2
    class2 = label_encoder.inverse_transform([indices[1]])[0]
    conf2 = test_proba[i, indices[1]] * 100

    # Top-3
    class3 = label_encoder.inverse_transform([indices[2]])[0]
    conf3 = test_proba[i, indices[2]] * 100

    results.append({
        "predicted_traffic": class1,
        "confidence": conf1,

        "top2_traffic": class2,
        "top2_confidence": conf2,

        "top3_traffic": class3,
        "top3_confidence": conf3
    })

xgb_results = pd.DataFrame(results)

print(xgb_results.head(10))

def classify_traffic_top3(model, X, label_encoder):

    # Get probabilities
    probabilities = model.predict_proba(X)

    # Get top 3 classes
    top3_indices = np.argsort(
        probabilities,
        axis=1
    )[:, -3:][:, ::-1]

    results = []

    for i in range(len(X)):

        predictions = []

        for rank, class_index in enumerate(
            top3_indices[i],
            start=1
        ):

            class_name = label_encoder.inverse_transform(
                [class_index]
            )[0]

            confidence = probabilities[
                i, class_index
            ] * 100

            predictions.append({
                "rank": rank,
                "traffic_type": class_name,
                "confidence": round(confidence, 2)
            })

        results.append(predictions)

    return results

y_val_pred = xgb_model.predict(X_val)
y_val_proba = xgb_model.predict_proba(X_val)

print("Validation predictions generated.")
print("Prediction shape:", y_val_pred.shape)
print("Probability shape:", y_val_proba.shape)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)

accuracy = accuracy_score(y_val_encoded, y_val_pred)

precision = precision_score(
    y_val_encoded,
    y_val_pred,
    average="macro",
    zero_division=0
)

recall = recall_score(
    y_val_encoded,
    y_val_pred,
    average="macro",
    zero_division=0
)

f1 = f1_score(
    y_val_encoded,
    y_val_pred,
    average="macro",
    zero_division=0
)

weighted_f1 = f1_score(
    y_val_encoded,
    y_val_pred,
    average="weighted",
    zero_division=0
)

print("========== VALIDATION RESULTS ==========")
print(f"Accuracy       : {accuracy:.4f}")
print(f"Macro Precision: {precision:.4f}")
print(f"Macro Recall   : {recall:.4f}")
print(f"Macro F1       : {f1:.4f}")
print(f"Weighted F1    : {weighted_f1:.4f}")

print("\n========== CLASSIFICATION REPORT ==========")

print(
    classification_report(
        y_val_encoded,
        y_val_pred,
        target_names=label_encoder.classes_,
        digits=4,
        zero_division=0
    )
)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

y_test_pred = xgb_model.predict(X_test)

xgb_test_accuracy = accuracy_score(
    y_test_encoded,
    y_test_pred
)

xgb_test_precision = precision_score(
    y_test_encoded,
    y_test_pred,
    average="macro",
    zero_division=0
)

xgb_test_recall = recall_score(
    y_test_encoded,
    y_test_pred,
    average="macro",
    zero_division=0
)

xgb_test_f1 = f1_score(
    y_test_encoded,
    y_test_pred,
    average="macro",
    zero_division=0
)

xgb_test_weighted_f1 = f1_score(
    y_test_encoded,
    y_test_pred,
    average="weighted",
    zero_division=0
)

print("============================================")
print("XGBOOST FINAL TEST EVALUATION")
print("============================================")

print(f"Accuracy        : {xgb_test_accuracy:.4f}")
print(f"Macro Precision : {xgb_test_precision:.4f}")
print(f"Macro Recall    : {xgb_test_recall:.4f}")
print(f"Macro F1        : {xgb_test_f1:.4f}")
print(f"Weighted F1     : {xgb_test_weighted_f1:.4f}")

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(
    y_val_encoded,
    y_val_pred
)

plt.figure(figsize=(12, 10))

plt.imshow(cm)

plt.title("XGBoost Validation Confusion Matrix")
plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")

plt.xticks(
    range(len(label_encoder.classes_)),
    label_encoder.classes_,
    rotation=90
)

plt.yticks(
    range(len(label_encoder.classes_)),
    label_encoder.classes_
)

plt.colorbar()

plt.tight_layout()
plt.show()

y_test_pred = xgb_model.predict(X_test)

print(
    classification_report(
        y_test_encoded,
        y_test_pred,
        target_names=label_encoder.classes_,
        digits=4,
        zero_division=0
    )
)

import os
import joblib

MODEL_DIR = MODELS_PATH

os.makedirs(MODEL_DIR, exist_ok=True)

# Save XGBoost model
xgb_model.save_model(
    str(MODEL_DIR / "xgboost_traffic_classifier.json")
)

# Save label encoder
joblib.dump(
    label_encoder,
    MODEL_DIR / "label_encoder.pkl"
)

# Save feature names
joblib.dump(
    feature_columns,
    MODEL_DIR / "feature_names.pkl"
)

print("XGBoost model and supporting files saved successfully.")

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

# XGBoost predictions
y_test_pred = xgb_model.predict(X_test)

# Convert prediction to integer if necessary
y_test_pred = y_test_pred.astype(int)

# Convert numeric predictions back to traffic names
y_test_pred_labels = label_encoder.inverse_transform(y_test_pred)

# Confusion matrix using string labels on both sides
cm = confusion_matrix(y_test, y_test_pred_labels)

# Plot
plt.figure(figsize=(12, 10))
plt.imshow(cm)

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("XGBoost Traffic Classification - Test Confusion Matrix")
plt.colorbar()

plt.xticks(
    range(len(label_encoder.classes_)),
    label_encoder.classes_,
    rotation=90
)

plt.yticks(
    range(len(label_encoder.classes_)),
    label_encoder.classes_
)

plt.tight_layout()
plt.show()

print("y_test type:", type(y_test.iloc[0]))
print("prediction type:", type(y_test_pred[0]))

print("\nFirst 10 actual:")
print(y_test.iloc[:10].values)

print("\nFirst 10 predicted:")
print(y_test_pred_labels[:10])

"""Anomoly Detection - Isolation Forest"""

import numpy as np
import pandas as pd
import joblib

from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler

features = [
    "duration",
    "total_fiat",
    "total_biat",
    "min_fiat",
    "min_biat",
    "max_fiat",
    "max_biat",
    "mean_fiat",
    "mean_biat",
    "flowPktsPerSecond",
    "flowBytesPerSecond",
    "min_flowiat",
    "max_flowiat",
    "mean_flowiat",
    "std_flowiat",
    "min_active",
    "mean_active",
    "max_active",
    "std_active",
    "min_idle",
    "mean_idle",
    "max_idle",
    "std_idle"
]

print("Number of Isolation Forest features:", len(features))
print(features)

# ============================================
# ISOLATION FOREST INPUT DATA
# ============================================

X_if_train = X_train[features].copy()
X_if_val = X_val[features].copy()
X_if_test = X_test[features].copy()

print("X_if_train:", X_if_train.shape)
print("X_if_val  :", X_if_val.shape)
print("X_if_test :", X_if_test.shape)

print("\nIsolation Forest feature count:",
      X_if_train.shape[1])

print("Isolation Forest features:")
print(X_if_train.columns.tolist())

print("\nNumber of features:", X_if_train.shape[1])

print("\nNon-numeric columns:")
print(X_if_train.select_dtypes(exclude=np.number).columns.tolist())

print("\nTarget present:",
      "traffic_type" in X_if_train.columns)

print("========== ISOLATION FOREST DATA CHECK ==========")

print("\nMissing values:")
print("Train:", X_if_train.isna().sum().sum())
print("Validation:", X_if_val.isna().sum().sum())
print("Test:", X_if_test.isna().sum().sum())

print("\nInfinite values:")
print("Train:", np.isinf(X_if_train).sum().sum())
print("Validation:", np.isinf(X_if_val).sum().sum())
print("Test:", np.isinf(X_if_test).sum().sum())

print("\nNegative values:")
print("Train:", (X_if_train < 0).sum().sum())
print("Validation:", (X_if_val < 0).sum().sum())
print("Test:", (X_if_test < 0).sum().sum())

scaler_if = RobustScaler()

X_if_train_scaled = scaler_if.fit_transform(X_if_train)

X_if_val_scaled = scaler_if.transform(X_if_val)

X_if_test_scaled = scaler_if.transform(X_if_test)

print("Scaled train shape:", X_if_train_scaled.shape)
print("Scaled validation shape:", X_if_val_scaled.shape)
print("Scaled test shape:", X_if_test_scaled.shape)

# ============================================
# ISOLATION FOREST MODEL TRAINING
# ============================================

from sklearn.ensemble import IsolationForest

isolation_forest = IsolationForest(
    n_estimators=200,
    contamination=0.10,
    random_state=42,
    n_jobs=-1
)

isolation_forest.fit(X_if_train_scaled)

print("Isolation Forest fitted successfully.")

train_predictions = isolation_forest.predict(X_if_train_scaled)
val_predictions = isolation_forest.predict(X_if_val_scaled)
test_predictions = isolation_forest.predict(X_if_test_scaled)

print("TRAIN")
print(pd.Series(train_predictions).value_counts())

print("\nVALIDATION")
print(pd.Series(val_predictions).value_counts())

print("\nTEST")
print(pd.Series(test_predictions).value_counts())

# ============================================
# ISOLATION FOREST RAW SCORES
# ============================================

train_raw_scores = isolation_forest.score_samples(
    X_if_train_scaled
)

val_raw_scores = isolation_forest.score_samples(
    X_if_val_scaled
)

test_raw_scores = isolation_forest.score_samples(
    X_if_test_scaled
)

print("Raw scores calculated successfully.")

print("Train:", len(train_raw_scores))
print("Validation:", len(val_raw_scores))
print("Test:", len(test_raw_scores))

# ============================================
# ANOMALY SCORE CALIBRATION
# ============================================

train_score_min = train_raw_scores.min()
train_score_max = train_raw_scores.max()

def convert_to_anomaly_score(raw_scores):

    anomaly_scores = (
        (train_score_max - raw_scores)
        /
        (train_score_max - train_score_min)
    ) * 100

    return np.clip(anomaly_scores, 0, 100)

train_anomaly_scores = convert_to_anomaly_score(
    train_raw_scores
)

val_anomaly_scores = convert_to_anomaly_score(
    val_raw_scores
)

test_anomaly_scores = convert_to_anomaly_score(
    test_raw_scores
)

print("Anomaly score calibration completed.")

print("Train range:",
      train_anomaly_scores.min(),
      "-",
      train_anomaly_scores.max())

print("Validation range:",
      val_anomaly_scores.min(),
      "-",
      val_anomaly_scores.max())

print("Test range:",
      test_anomaly_scores.min(),
      "-",
      test_anomaly_scores.max())

print("y_test:", len(y_test))
print("X_if_test:", len(X_if_test))
print("test_anomaly_scores:", len(test_anomaly_scores))
print("test_predictions:", len(test_predictions))

assert len(X_if_test_scaled) == len(y_test)
assert len(test_predictions) == len(y_test)
assert len(test_anomaly_scores) == len(y_test)

print("All test arrays have matching lengths.")

test_results = pd.DataFrame({
    "traffic_type": y_test.values,
    "anomaly_score": test_anomaly_scores,
    "prediction": test_predictions
})

test_results["status"] = test_results["prediction"].map({
    1: "NORMAL",
    -1: "ANOMALY"
})

print(test_results.head(10))

print("========== ANOMALY SUMMARY ==========")

print("Total test flows:", len(test_results))

print(
    "Normal flows:",
    (test_results["status"] == "NORMAL").sum()
)

print(
    "Anomalous flows:",
    (test_results["status"] == "ANOMALY").sum()
)

print(
    "Anomaly percentage:",
    (test_results["status"] == "ANOMALY").mean() * 100
)

print("========== SCORE INTERPRETATION ==========")

print("\nMost normal flows:")
print(
    test_results[
        test_results["status"] == "NORMAL"
    ][["traffic_type", "anomaly_score", "status"]]
    .sort_values("anomaly_score")
    .head(10)
)

print("\nMost suspicious flows:")
print(
    test_results[
        test_results["status"] == "ANOMALY"
    ][["traffic_type", "anomaly_score", "status"]]
    .sort_values("anomaly_score", ascending=False)
    .head(10)
)

# ============================================
# SEPARATE NORMAL AND ANOMALOUS TEST FLOWS
# ============================================

# Reset indices so X_if_test and test_results
# use the same positional index
X_if_test_reset = X_if_test.reset_index(drop=True)

normal_mask = test_results["prediction"] == 1
anomaly_mask = test_results["prediction"] == -1

normal_flows = X_if_test_reset.loc[normal_mask].copy()
anomaly_flows = X_if_test_reset.loc[anomaly_mask].copy()

print("============================================")
print("TEST FLOW SEPARATION")
print("============================================")

print("Normal flows   :", len(normal_flows))
print("Anomalous flows:", len(anomaly_flows))

print("\nCheck:")
print("Total flows    :", len(normal_flows) + len(anomaly_flows))
print("Expected flows :", len(X_if_test_reset))

top_suspicious = test_results.sort_values(
    "anomaly_score",
    ascending=False
).head(10)

print("========== TOP 10 SUSPICIOUS FLOWS ==========")

print(
    top_suspicious[
        [
            "traffic_type",
            "anomaly_score",
            "status"
        ]
    ]
)

# ============================================
# FEATURES OF TOP SUSPICIOUS TEST FLOWS
# ============================================

# These are POSITIONAL indices
top_suspicious_indices = top_suspicious.index.to_numpy()

# Use iloc because indices represent row positions
top_suspicious_features = X_if_test.iloc[top_suspicious_indices].copy()

# Get corresponding traffic types using the same positions
top_suspicious_features["traffic_type"] = (
    y_test.iloc[top_suspicious_indices].values
)

# Add anomaly score
top_suspicious_features["anomaly_score"] = (
    test_anomaly_scores[top_suspicious_indices]
)

print("============================================================")
print("TOP SUSPICIOUS FLOW FEATURES")
print("============================================================")

print(top_suspicious_features.to_string())

isolation_results = test_results.copy()

print(isolation_results.head())

isolation_results_path = (
    REPORTS_PATH / "isolation_forest_test_results.csv"
)

isolation_results.to_csv(
    isolation_results_path,
    index=False
)

print("Isolation Forest results saved to:")
print(isolation_results_path)

# ============================================
# EXPLICIT USER INPUT - ISOLATION FOREST
# ============================================

def detect_anomaly(flow_features):

    # Check number of features
    if len(flow_features) != len(features):
        raise ValueError(
            f"Expected {len(features)} features, "
            f"but received {len(flow_features)}."
        )

    # Reload artifacts to simulate backend inference
    loaded_if = joblib.load(MODELS_PATH / "isolation_forest.pkl")
    loaded_scaler = joblib.load(MODELS_PATH / "isolation_forest_scaler.pkl")
    loaded_cal = joblib.load(MODELS_PATH / "anomaly_calibration.pkl")

    # Convert user input to DataFrame
    input_df = pd.DataFrame(
        [flow_features],
        columns=features
    )

    # Make sure all values are numeric
    input_df = input_df.apply(
        pd.to_numeric,
        errors="raise"
    )

    # Apply the SAME scaler fitted on training data
    input_scaled = loaded_scaler.transform(input_df)

    # Isolation Forest prediction
    prediction = loaded_if.predict(input_scaled)[0]

    # Internal score
    raw_score = loaded_if.score_samples(input_scaled)[0]

    # Convert using TRAINING calibration
    t_min = loaded_cal["train_score_min"]
    t_max = loaded_cal["train_score_max"]
    anomaly_score = ((t_max - raw_score) / (t_max - t_min)) * 100
    anomaly_score = np.clip(anomaly_score, 0, 100)

    # Final status
    status = (
        "ANOMALY"
        if prediction == -1
        else "NORMAL"
    )

    return {
        "status": status,
        "anomaly_score": round(float(anomaly_score), 2)
    }

# ============================================
# EXPORT ISOLATION FOREST ARTIFACTS
# ============================================

joblib.dump(isolation_forest, MODELS_PATH / "isolation_forest.pkl")
joblib.dump(scaler_if, MODELS_PATH / "isolation_forest_scaler.pkl")
joblib.dump(features, MODELS_PATH / "isolation_forest_features.pkl")
anomaly_calibration = {
    "train_score_min": train_score_min,
    "train_score_max": train_score_max
}
joblib.dump(anomaly_calibration, MODELS_PATH / "anomaly_calibration.pkl")

print("Isolation Forest artifacts saved successfully.")

# ============================================
# ARTIFACT VERIFICATION
# ============================================

print("\n========== MODEL ARTIFACT VERIFICATION ==========")
artifacts_to_check = [
    "xgboost_traffic_classifier.json",
    "label_encoder.pkl",
    "feature_names.pkl",
    "imputation_medians.pkl",
    "isolation_forest.pkl",
    "isolation_forest_scaler.pkl",
    "anomaly_calibration.pkl",
    "isolation_forest_features.pkl"
]

all_ok = True
for artifact in artifacts_to_check:
    artifact_path = MODELS_PATH / artifact
    if artifact_path.exists() and artifact_path.stat().st_size > 0:
        print(f"{artifact.split('.')[0].replace('_', ' ').title()}: OK")
    else:
        print(f"{artifact.split('.')[0].replace('_', ' ').title()}: FAILED")
        all_ok = False

print(f"\nFeature count: {len(feature_columns)}")

if all_ok:
    print("\nAll model artifacts ready for backend integration.")
else:
    print("\nWarning: Some artifacts are missing or empty.")

# ============================================
# MODEL RELOAD AND TEST
# ============================================

print("\n========== RELOAD TEST ==========")
try:
    # Reload XGBoost
    xgb_reloaded = XGBClassifier()
    xgb_reloaded.load_model(str(MODELS_PATH / "xgboost_traffic_classifier.json"))
    le_reloaded = joblib.load(MODELS_PATH / "label_encoder.pkl")
    fn_reloaded = joblib.load(MODELS_PATH / "feature_names.pkl")
    
    # Reload Isolation Forest
    if_reloaded = joblib.load(MODELS_PATH / "isolation_forest.pkl")
    scaler_reloaded = joblib.load(MODELS_PATH / "isolation_forest_scaler.pkl")
    cal_reloaded = joblib.load(MODELS_PATH / "anomaly_calibration.pkl")
    
    # Test XGBoost
    test_idx = 0
    sample_x = X_test.iloc[[test_idx]]
    orig_pred = xgb_model.predict(sample_x)[0]
    reload_pred = xgb_reloaded.predict(sample_x)[0]
    if orig_pred == reload_pred:
        print("XGBoost reload: PASS")
    else:
        print("XGBoost reload: FAIL")
        
    # Test Isolation Forest
    sample_if = X_if_test.iloc[[test_idx]]
    orig_if_pred = isolation_forest.predict(scaler_if.transform(sample_if))[0]
    reload_if_pred = if_reloaded.predict(scaler_reloaded.transform(sample_if))[0]
    if orig_if_pred == reload_if_pred:
        print("Isolation Forest reload: PASS")
    else:
        print("Isolation Forest reload: FAIL")
except Exception as e:
    print(f"Reload test failed with error: {e}")

# ============================================
# TEST EXPLICIT FLOW
# ============================================

sample_flow = X_if_test.iloc[0].tolist()

result = detect_anomaly(sample_flow)

print("============================================")
print("ISOLATION FOREST EXPLICIT INPUT TEST")
print("============================================")

print("Status:", result["status"])
print("Anomaly Score:", result["anomaly_score"], "/100")